<?php

namespace Test\Games;

use Phalcon\Di;

abstract class UnitTestCase extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Di
     */
    protected $di;

    public static function setUpBeforeClass() {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }


    public function setUp() {
        $this->di = Di::getDefault();
    }

}